### ISSUE TITLE
Platform icons missing on Firefox build

### ISSUE THREAD

**Issue by Luckz** [jshackles/Enhanced_Steam_Firefox#114]
Steam Store pages don't show the platform icons above the Add to Cart button. Somehow HTC Vive is immune, see http://store.steampowered.com/app/610680/Starway_Fleet/ as an example.

http://ft.trillian.im/c27ecec70eb02d421b83464ad07d3abe9ef772fe/6Tda4Lc89ervzd8AA9NGmI6ZGu9Pc.jpg

**Comment by Corben78** [comment]
Looks like the (relative) URL for the background image is not working.

Without Enhanced Steam the css defines:
```css
background-image: url( '/public/images/v6/icon_platform_linux.png' );
```
With Enhanced Steam:
```css
background-image: url( '//steamstore-a.akamaihd.net/public/images/v6/icon_platform_linux.png' );
```
When I change in firefox webdev tools the css to match the original css, (removing //steamstore-a.akamaihd.net), the image still cannot be loaded (moz-extension://d4e12e0c-15b1-40b3-9b23-8de873b0e284/public/images/v6/icon_platform_linux.png could not be found).
When I put ```http:``` in front of it, it works:
```css
background-image: url( 'http://steamstore-a.akamaihd.net/public/images/v6/icon_platform_linux.png' );
```

Don't know how to handle this properly in the css of enhanced steam, so it shows a relative path. But with an absolute URL it works.

With Chrome it seems that the css definitions for span.platform_img.linux are ignored from enhancedsteam.css. The active css shown is store.css from store.steampowered.com, the lines from enhancedsteam.css are strucked out and it says injected stylesheet next to it.

**Comment by c12h** [comment]
The problem is `css/enhancedsteam.css`, at lines 15-42, which were added in 2013 (["Adds platform icon to wishlist page games" - commit a2abd7d](https://github.com/jshackles/Enhanced_Steam/commit/a2abd7dd8d563708d85c223d0b2aebc5d7276f2b)). These CSS rules affect both app pages and wishlists, presumably to ensure consistency. The lines specifying icons were changed last February (["Fixed mixed content warnings" - commit 7a8a93a](https://github.com/jshackles/Enhanced_Steam/commit/7a8a93a3ecc9c265b16c09262d3cd55e8ebe8da9)). Unfortunately, the latter fix does not work under Firefox, in which URLs in CSS rules get expanded relative to `moz-extension://…` rather than the document's URL.

We could get the icons back on app pages by making these CSS rules only apply on wishlist pages. This can be done by inserting `span.es_platform > ` at the start of every selector, like this:
```css
span.es_platform > span.platform_img.win {
	background-image: url( '//steamstore-a.akamaihd.net/public/images/v6/icon_platform_win.png' );
}
```

AFAICS, getting the icons back on wishlist pages requires browser-dependent URLs: `//steamstore-a.akamaihd.net/…` on Chrome, `https://steamstore-a.akamaihd.net/…` on Firefox. (This forces the icons to be fetched via HTTPS even when viewing a wishlist via HTTP, but that's not a major problem and I cannot see how to avoid it.) Perhaps we should just have different versions of `css/enhancedsteam.css` for Enhanced_Steam and Enhanced_Steam_Firefox?

**Comment by c12h** [comment]
**Workaround**  Here is a somewhat ugly fix for this problem. It uses a file named [`userContent.css`](http://kb.mozillazine.org/UserContent.css) in your Firefox profile, so first you have to find your Firefox profile directory. (If you don't know how to do that, open the address "about:support" in a new Firefox tab, then click on the "Open Directory" button in the "Application Basics" section to get a file manager window in which the directory with the gobbledygook name is your profile directory. Open that directory.)

1. See if the profile directory has a folder named "chrome". If not, create one, using only lower-case letters (no capital letters).
1. If you have a file named userContent.css there, edit it. If not, create it. (Only one capital letter.)
1. Copy and paste the CSS shown below into your userContent.css and save the edits.
1. Restart Firefox.
```CSS
@-moz-document	domain(store.steampowered.com), domain(steamcommunity.com)
{
  span.platform_img.steamplay {
	background-image: url( 'https://steamstore-a.akamaihd.net/public/images/v6/icon_platform_linux.png' ) !important;
  }
  span.platform_img.win {
	background-image: url( 'https://steamstore-a.akamaihd.net/public/images/v6/icon_platform_win.png' )  !important;
  }
  span.platform_img.mac {
	background-image: url( 'https://steamstore-a.akamaihd.net/public/images/v6/icon_platform_mac.png' )  !important;
  }
  span.platform_img.linux {
	background-image: url( 'https://steamstore-a.akamaihd.net/public/images/v6/icon_platform_linux.png' ) !important;
  }
}
```
